// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Task struct {
	ID          interface{}
	Userid      interface{}
	Task        string
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        interface{}
	Name      string
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
